/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.0   2017-10-29

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"

extern "C"{
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"
#include "semphr.h"
}

#include "radio/bsp.h"
#include "radio/commands.h"

void vTaskLed1( void *pvParameters){
	//const char *pcTaskName = "Task 1 is running \r\n";
	//volatile uint32_t ul;

	//configASSERT( ( ( uint32_t ) pvParameters ) == 1 );
	//a tarefa tem implementada nela um loop infinito.
	for(;;){
		int delay;
		delay = pdMS_TO_TICKS(1000);
		vTaskDelay(delay);
		GPIOD->ODR ^= GPIO_Pin_13;

	}
}
void vTaskLed2( void *pvParameters){
	//const char *pcTaskName = "Task 1 is running \r\n";
	//volatile uint32_t ul;
	NRF24L01P *_nrf24;
	_nrf24->Init();
	_nrf24->Config();
	//configASSERT( ( ( uint32_t ) pvParameters ) == 1 );
	//a tarefa tem implementada nela um loop infinito.
	for(;;){
		int delay;
		delay = pdMS_TO_TICKS(100);
		vTaskDelay(delay);
		GPIOD->ODR ^= GPIO_Pin_12;


	}
}
void vTask2( void *pvParameters){
	for(;;){
		int delay;
		delay = pdMS_TO_TICKS(10);
		vTaskDelay(delay);

		usb_device_class_cdc_vcp.GetData(_usbserialbuffer, 1024);
		cmdline.In(_usbserialbuffer);
		cmdline.Out(_usbserialbuffer);
		if(_usbserialbuffer.Ocupied()){
			usb_device_class_cdc_vcp.SendData(_usbserialbuffer);
		}
	}
}

int main(void)
{
  int i = 0;
  usb.Init();
  SysTick_Config(SystemCoreClock/1000);
  GPIO_InitTypeDef  GPIO_InitStructure;

    /* Enable the GPIO_LED Clock */
   RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);

    /* Configure the GPIO_LED pin */
   GPIO_InitStructure.GPIO_Pin = GPIO_Pin_13;
   GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
   GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
   GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
   GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
   GPIO_Init(GPIOD, &GPIO_InitStructure);

   GPIO_InitStructure.GPIO_Pin = GPIO_Pin_12;
   GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
   GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
   GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
   GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
   GPIO_Init(GPIOD, &GPIO_InitStructure);

   xTaskCreate(	vTaskLed1, //ponteiro para a função que implementa a tarefa
		  "Task Led1", 	//nome da função. Para facilitar o debug.
		  150, 		//stack depth
		  NULL, 		//nao usa task parameter
		  1,			//prioridade 1
		  NULL);
   xTaskCreate(	vTaskLed2, //ponteiro para a função que implementa a tarefa
		  "Task Led2", 	//nome da função. Para facilitar o debug.
		  700, 		//stack depth
		  NULL, 		//nao usa task parameter
		  1,			//prioridade 1
		  NULL);
   xTaskCreate(	vTask2, //ponteiro para a função que implementa a tarefa
		  "Task 2", 	//nome da função. Para facilitar o debug.
		  700, 		//stack depth
		  NULL, 		//nao usa task parameter
		  1,			//prioridade 1
		  NULL);
  vTaskStartScheduler();
  while (1)
  {
	//i++;
  }
}


extern "C" void vApplicationStackOverflowHook( xTaskHandle pxTask, signed char *pcTaskName ){
	( void ) pcTaskName;
	( void ) pxTask;
	for( ;; );
}

extern "C" void vApplicationIdleHook( void ){
	volatile size_t xFreeStackSpace;
	xFreeStackSpace = xPortGetFreeHeapSize();
}

extern "C" void vApplicationTickHook( void ){
}

extern "C" void vApplicationMallocFailedHook( void ){
	for( ;; );
}

